### ISSUE TITLE
Error in registering component in Vue

### ISSUE THREAD

**Issue by pongoman** [AlexMordred/vue-tagsinput#2]
Hello,

When using `Vue.component('tags-input', require('@voerro/vue-tagsinput'));` in an enviroment created through vue-cli webpack template, an error is produced: vue is not defined.

I bypassed it using the full path for import `import TagsInput from '@voerro/vue-tagsinput/src/TagsInput.vue'` and then registering it.

**Comment by AlexMordred** [comment]
Hello.

Thanks for reporting this! I updated the package, please check if the problem has gone. Also, you might need to add this line if backspace stops working:

```javascript
Vue.config.keyCodes.backspace = 8;
```

**Comment by pongoman** [comment]
Hi,
I have re-installed the package and using only this line `Vue.component('tags-input', require('@voerro/vue-tagsinput'));` in `main.js` for registering produces: `[Vue warn]: Failed to mount component: template or render function not defined.`

**Comment by AlexMordred** [comment]
I've encountered that also and I'm not sure why does it work like that. Currently it works fine in my Laravel project. Check if this fixes the problem:

```javascript
Vue.component('tags-input', require('@voerro/vue-tagsinput').default);
```

**Comment by pongoman** [comment]
That did it! Thanks

**Comment by AlexMordred** [comment]
Great! 👍
