### ISSUE TITLE
Suggestion: You can easily add v-model support

### ISSUE THREAD

**Issue by sitmsc** [AlexMordred/vue-tagsinput#3]
Hello, first of all simple & great component and I'm sorry if this is the wrong spot for suggestions.

I wanted to use Vue's v-model directive and it took around one minute to implement. Maybe you'd like to use this too:

Append "value" to props:
  props: ['elementId', 'existingTags', 'oldTags', 'typeahead', 'value'],

Emit an input event after a tag has been added / removed (add this to the "tag()" watcher):
  this.$emit('input', this.tags);

You can then use your component like:
<tags-input ... v-model="selectedTags"/>

Cheers

**Comment by AlexMordred** [comment]
Hello and thank you. I don't know if there's any other place for suggestions, so I guess it's ok.

Let me clarify, what format do you need that data in?

**Comment by rebotak** [comment]
how did you apply v-model support to this vue-tagsinput?

**Comment by AlexMordred** [comment]
I haven't yet, sorry. I'll try to add it tomorrow if I have time.

**Comment by AlexMordred** [comment]
I've implemented the `v-model` support, please update the package.
