### ISSUE TITLE
how to limit the selected?

### ISSUE THREAD

**Issue by rebotak** [AlexMordred/vue-tagsinput#4]
how can I limit the selected to 3?

**Comment by AlexMordred** [comment]
I'm yet to implement this feature, although it's really simple. For now you can edit the `addTag(slug, text) ` method in the `src/TagsInput.vue`. Just add this at the top:

```
if (this.tags.length >= 3) {
   return;
}
```

I'll update the README and close this issue after implementing the functionality.

**Comment by rebotak** [comment]
okaay, will do that, thank you

**Comment by AlexMordred** [comment]
I've updated the package, there's "limit" now.
